### PR TITLE
Remove duplicate @

### PR DESCRIPTION
**Pull request by rmartinoscar**
image
image
image
image

Just showing that there's not any `@` in their name

### CODE REVIEW

**Comment by parkervcp** [comment]
This is not an issue with the bot. It's an issue with the config.

**Comment by parkervcp** [comment]
I see what you mean now. The default example config will have this issue. I thought this was an issue and not a PR to fix the defaults.

**Comment by parkervcp** [comment]
i still don't know why the supportbot and pelitron add extra `@'s` in places. The configs don't have them either.

**Comment by rmartinoscar** [comment]
> i still don't know why the supportbot and pelitron add extra `@'s` in places. The configs don't have them either.

https://github.com/parkervcp/parkertron/blob/35393d928b61000b71f471437ca97ec18762725b/discord.go#L383

**Pull request merged**
