### PR TITLE
Regex patterns

### PR DESCRIPTION
**Pull request by JonasDev17**
This PR adds the ability to configure regex patterns. They can be configured exactly like keywords:

```
 patterns:
  - pattern: ".*abc.*"
    reaction:
    - ""
    response:
    - I have found to the word abc somewhere in there.
```

### CODE REVIEW

**Comment by parkervcp** [comment]
I feel like "regex" is better than "patterns" for a type here.

Like this
```
 regex:
  - pattern: ".*abc.*"
    reaction:
    - ""
    response:
    - I have found to the word abc somewhere in there.
```

**Comment by JonasDev17** [comment]
or what do you think about the ability to define multiple patterns / keywords for one response?
like:

```
regex:
  - patterns: { ".*abc.*", ".*test.*"}
    reaction:
    - ""
    response:
    - I have found the word abc somewhere in there.
```

But I don't know how you would do keywords?

```
keywords:
  - keywords: { "example", "test"}
    reaction:
    - ""
    response:
    - I have found the word abc somewhere in there.
```

**Comment by parkervcp** [comment]
yaml actually already supports that. You can place references and pointers in it.

```yaml
      - keyword: "hello"
        reaction: &hello_reaction
          - "👋"
        response: &hello_response
          - Hello
        exact: true

      - keyword: "heyo"
        reaction: *hello_reaction
        response: *hello_response
        exact: true
```

**Comment by parkervcp** [comment]
For short keywords it might be better to have it in a single line but for the longer keywords it become an issue.

**Comment by parkervcp** [comment]
defining multiple patterns would be nice but I think the yaml references are probably the better way to support this.

**Comment by JonasDev17** [comment]
Yeah, makes sense 👍 so since yaml already supports this, does that also mean the parser already supports it or is that something that has to be implemented?

**Comment by parkervcp** [comment]
It's already built in.

**Pull request merged**
